---
- name: Create DB names and Admin users Drupal and CiviCRM
  hosts: remote_db-drupal
  become: yes

  vars_files:
      - templates/mysql/servers.vars.yml

  tasks:
  - include: tasks/user-root_mysql.yml
  - include: tasks/user-drupal_mysql.yml
  - include: tasks/user-civicrm_mysql.yml
