---
# frontend_site-create.yml - palybook Ansible
#
# maintained by:  Eugene Reut <eugene.reut@gmail.com>
# Please ALWAYS copy eugene.reut@gmail.com
# on emails.
#
# Copyright 2018 Eugene Reut
#
# This file is part of Devops/Sysadmin Task.
#
#    Devops/Sysadmin Task is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Devops/Sysadmin Task is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Devops/Sysadmin Task.  If not, see <https://www.gnu.org/licenses/>.

- name: Let's Encrypt certbot and Nginx SSL Site Create
  hosts: remote_web
  become: yes

  vars_files:
      - templates/mysql/servers.vars.yml

  tasks:
      # tasks for development site with Self signed SSL cert
      #- include: tasks/letsencrypt-development.yml
      #- include: tasks/le_nginx-config-production.yml

      # tasks for production site with SSL Let's Encrypt certbot
      - include: tasks/letsencrypt-production.yml
      - include: tasks/le_nginx-config-production.yml

  handlers:
      - include: handlers.yml
