---
# fail2ban.yml - tasks Ansible
#
# maintained by:  Eugene Kostryuchin <eugene.kostryuchin@gmail.com>
# Please ALWAYS copy eugene.kostryuchin@gmail.com
# on emails.
#
# Copyright 2018 Eugene Kostryuchin
#
# This file is part of Devops/Sysadmin Task.
#
#    Devops/Sysadmin Task is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Devops/Sysadmin Task is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Devops/Sysadmin Task.  If not, see <https://www.gnu.org/licenses/>.

# https://www.fail2ban.org/wiki/index.php/Main_Page
- name: Install fail2ban
  apt: package=fail2ban state=present

# Please check all Vars in
# templates/mysql/servers.vars.yml
# templates/fail2ban.conf.j2
- name: Copy fail2ban default config
  template: src=templates/fail2ban.conf.j2 dest=/etc/fail2ban/jail.local
  notify:
    - restart fail2ban
