---
# le_nginx-config-development.yml - tasks Ansible
#
# maintained by:  Eugene Kostryuchin <eugene.kostryuchin@gmail.com>
# Please ALWAYS copy eugene.kostryuchin@gmail.com
# on emails.
#
# Copyright 2018 Eugene Kostryuchin
#
# This file is part of Devops/Sysadmin Task.
#
#    Devops/Sysadmin Task is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Devops/Sysadmin Task is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Devops/Sysadmin Task.  If not, see <https://www.gnu.org/licenses/>.

# Run this script if webserver is development 
# file uncomment in playbook: frontend_site-create.yml
- name: Disable nginx default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Remove nginx default site config
  file: path=/etc/nginx/sites-available/default state=absent

- name: Deploy nginx site config
  template: src=templates/nginx-site-ssl_dev.conf.j2 dest=/etc/nginx/sites-available/{{ servers_vars.frontend_hostname }} owner=root
  notify:
      -  test nginx and reload

- name: Activate nginx site
  file: src=/etc/nginx/sites-available/{{ servers_vars.frontend_hostname }} dest=/etc/nginx/sites-enabled/{{ servers_vars.frontend_hostname }} state=link owner=root
  notify:
      -  test nginx and reload
