---

- name: Install php
  apt: package={{ item }} state=present
  with_items:
    - php7.0
    - php7.0-cli
    - php7.0-json
    - php7.0-mysql
    - php7.0-curl
    - php7.0-mcrypt
    - php7.0-gd
    - php-imagick
    - php7.0-fpm
    - php7.0-common
    - php7.0-odbc
    - php7.0-mbstring
    - php7.0-xmlrpc
    - php7.0-opcache
    - php7.0-intl
    - php7.0-bz2
    - php7.0-xml
    - php-ssh2

- name:  enable phpenmod
  command: phpenmod curl

# php.ini Development
# https://www.drupal.org/docs/7/system-requirements/drupal-7-php-requirements
#- name: Modify php.ini settings
#  copy: src=templates/php.ini-development dest=/etc/php/7.0/fpm/php.ini
#  notify:
#    - restart php-fpm

# php.ini Production
# https://www.drupal.org/docs/7/system-requirements/drupal-7-php-requirements
- name: Modify php.ini settings
  copy: src=templates/php.ini-production dest=/etc/php/7.0/fpm/php.ini
  notify:
    - restart php-fpm
