---
# user-drupal_mysql.yml - tasks Ansible
#
# maintained by:  Eugene Kostryuchin <eugene.kostryuchin@gmail.com>
# Please ALWAYS copy eugene.kostryuchin@gmail.com
# on emails.
#
# Copyright 2018 Eugene Kostryuchin
#
# This file is part of Devops/Sysadmin Task.
#
#    Devops/Sysadmin Task is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Devops/Sysadmin Task is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Devops/Sysadmin Task.  If not, see <https://www.gnu.org/licenses/>.

# grant USAGE access for the Drupal admin user to all the Drupal tables
- name: Ensure Drupal admin for Drupal tables are present
  mysql_user:
      name: "{{ drupal_db.user }}"
      append_privs: true
      host: "%"
      password: "{{ drupal_db.password }}"
      priv: "{{ drupal_db.name }}.*:ALL"
      state: present

- name: Ensure Drupal MySQL databases are present
  mysql_db:
      name: "{{ drupal_db.name }}"
      collation: "utf8_general_ci"
      encoding: "utf8"
      state: present

# grant USAGE access for the Drupal admin user to all the CiviCRM tables
- name: Ensure Drupal admin for CiviCRM tables are present
  mysql_user:
      name: "{{ drupal_db.user }}"
      append_privs: true
      host: "%"
      password: "{{ drupal_db.password }}"
      priv: "{{ civicrm_vars.name }}.*:ALL"
      state: present

- name: Ensure CiviCRM MySQL databases are present
  mysql_db:
      name: "{{ civicrm_vars.name }}"
      collation: "utf8_general_ci"
      encoding: "utf8"
      state: present
