---
# grant SELECT access for the Drupal admin user to all the Drupal tables
- name: Ensure Drupal admin for Drupal tables are present
  mysql_user:
      name: "{{ drupal_db.user }}"
      append_privs: true
      host: "%"
      password: "{{ drupal_db.password }}"
      priv: "{{ drupal_db.name }}.*:ALL"
      state: present

- name: Ensure Drupal MySQL databases are present
  mysql_db:
      name: "{{ drupal_db.name }}"
      collation: "utf8_general_ci"
      encoding: "utf8"
      state: present

# grant SELECT access for the Drupal admin user to all the CiviCRM tables
- name: Ensure Drupal admin for CiviCRM tables are present
  mysql_user:
      name: "{{ drupal_db.user }}"
      append_privs: true
      host: "%"
      password: "{{ drupal_db.password }}"
      priv: "{{ civicrm_vars.name }}.*:ALL"
      state: present

- name: Ensure CiviCRM MySQL databases are present
  mysql_db:
      name: "{{ civicrm_vars.name }}"
      collation: "utf8_general_ci"
      encoding: "utf8"
      state: present
